apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: neon-void
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: neon-void
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: neon-void
  labels:
    app.kubernetes.io/name: game-service
    app.kubernetes.io/part-of: neon-void
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: game-service
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: neon-void
  labels:
    app.kubernetes.io/name: ws-service
    app.kubernetes.io/part-of: neon-void
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app.kubernetes.io/name: ws-service
  ports:
    - name: ws
      port: 8080
      targetPort: ws
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: neon-void
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: neon-void
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
